### ISSUE TITLE
Bug : fail2ban status on systemd OSs 

### ISSUE THREAD

**Issue by nocternology** [oussemos/fail2ban-dashboard#4]
Hi there,

I just tried the dashboard, and i had a strange bug : when launching the webserver and going to localhost:5000, i get a : 
```
UnicodeDecodeError
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

I tracked down the problem to the variable status before the rendering of the homepage (line 32 of home.py), and i think it comes from the fact that on systemd OSs, the "service" command is translated to "systemctl" command; with systemctl, the output is this : 

![screenshot_2015-09-20_22-44-58](https://cloud.githubusercontent.com/assets/12981014/9982835/442c85c0-5fe9-11e5-840c-40ca3e1d0c61.png)

it has the little green led to indicate that the service is up, and that cannot be parsed by Jinja.

I will try to fix this problem and give a PR to make the fail2ban status checking more universal.

**Comment by oussemos** [comment]
Hi @nocternology, this tool was developed with Debian Wheezy (based on sysvinit) and wasn't tested with systemd.
Thanks and i'm waiting for your fix :+1: :)

**Comment by oussemos** [comment]
Good fix @nocternology :+1:
